var data = [
    // add new publications here
    // follow this template, retrieve data from YJ's google scholar
    /*
    {//72
        "Title":    "AJAX with deep learning",
        "Authors":  "J Yan, K Yang",
        "Journal":  "Nature",
        "Year":     "2019",
        "DOI":      "https://doi.org/10.1111/boc.201700061",
    },
    */
    /* ******* publication table data ******* */
    {//99
        "Title":    "Structural-elastic determination of the mechanical lifetime of biomolecules",
        "Authors":  "S Guo, Q Tang, M Yao, S Le, H Chen, J Yan",
        "Journal":  "Chemical Science",
        "Year":     "2018",
        "DOI":      "https://doi.org/10.1039/C8SC01319E",
    },
    {//98
        "Title":    "Transfer-matrix calculations of the effects of tension and torque constraints on DNA-protein interactions",
        "Authors":  "AK Efremov, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2018",
        "DOI":      "https://doi.org/10.1093/nar/gky478",
    },
    {//97
        "Title":    "Two-State Folding Energy Determination Based on Transition Points in Non-Equilibrium Single-Molecule Experiments",
        "Authors":  "H You, S Guo, S Le, Q Tang, M Yao, X Zhao, J Yan",
        "Journal":  "The Journal of Physical Chemistry Letters",
        "Year":     "2018",
        "DOI":      "https://doi.org/10.1021/acs.jpclett.7b03123",
    },
    {//96
        "Title":    "Tension-Dependent Stretching Activates ZO-1 to Control the Junctional Localization of Its Interactors",
        "Authors":  "D Spadaro, S Le, T Laroche, I Mean, L Jond, J Yan, S Citi",
        "Journal":  "Current Biology",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1016/j.cub.2017.11.014",
    },
    {//95
        "Title":    "Mechanical responses of the mechanosensitive unstructured domains in cardiac titin",
        "Authors":  "SM Pang, S Le, J Yan",
        "Journal":  "Biology of the Cell",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1111/boc.201700061",
    },
    {//94
        "Title":    "Mechanotransmission and Mechanosensing of Human alpha-Actinin 1",
        "Authors":  "S Le, X Hu, M Yao, H Chen, M Yu, X Xu, N Nakazawa, FM Margadant, MP Sheetz, J Yan",
        "Journal":  "Cell Reports",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1016/j.celrep.2017.11.040",
    },
    {//93
        "Title":    "mDia1 senses both force and torque during F-actin filament polymerization",
        "Authors":  "M Yu, X Yuan, C Lu, S Le, R Kawamura, AK Efremov, Z Zhao, MM Kozlov, M Sheetz, A Bershadsky, J Yan",
        "Journal":  "Nature Communications",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1038/s41467-017-01745-4",
    },
    {//92
        "Title":    "Non-canonical activation of OmpR drives acid and osmotic stress responses in single bacterial cells",
        "Authors":  "S Chakraborty, RS Winardhi, LK Morgan, J Yan, LJ Kenney",
        "Journal":  "Nature Communications",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1038/s41467-017-02030-0",
    },
    {//91
        "Title":    "Charged residues in the H-NS linker drive DNA binding and gene silencing in single cells",
        "Authors":  "Y Gao, YH Foo, RS Winardhi, Q Tang, J Yan, LJ Kenney",
        "Journal":  "PNAS",
        "Year":     "2017",
        "DOI":      "http://www.pnas.org/content/114/47/12560.abstract",
    },
    {//90
        "Title":    "Parallel triplex structure formed between stretched single-stranded DNA and homologous duplex DNA",
        "Authors":  "J Chen, Q Tang, S Guo, C Lu, S Le, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1093/nar/gkx628",
    },
    {//89
        "Title":    "Studying the mechanical responses of proteins using magnetic tweezers",
        "Authors":  "X Zhao, X Zeng, C Lu, J Yan",
        "Journal":  "Nanotechnology",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1088/1361-6528/aa837e",
    },
    {//88
        "Title":    "Bacillus subtilis RecA with DprA–SsbA antagonizes RecX function during natural transformation",
        "Authors":  "S Le, E Serrano, R Kawamura, B Carrasco, J Yan, JC Alonso",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1093/nar/gkx583",
    },
    {//87
        "Title":    "Oncofetal HMGA2 effectively curbs unconstrained (+) and (−) DNA supercoiling",
        "Authors":  "X Zhao, S Peter, P Dröge, J Yan",
        "Journal":  "Scientific Reports",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1038/s41598-017-09104-5",
    },
    {//86
        "Title":    "Elasticity of the Transition State Leading to an Unexpected Mechanical Stabilization of Titin Immunoglobulin Domains",
        "Authors":  "G Yuan, S Le, M Yao, H Qian, X Zhou, J Yan, H Chen",
        "Journal":  "Angewandte Chemie",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1002/ange.201700411",
    },
    {//85
        "Title":    "Theoretical Methods for Studying DNA Structural Transitions under Applied Mechanical Constraints",
        "Authors":  "AK Efremov, RS Winardhi, J Yan",
        "Journal":  "Polymers",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.3390/polym9020074",
    },
    {//84
        "Title":    "RHAU helicase stabilizes G4 in its nucleotide-free state and destabilizes G4 upon ATP hydrolysis",
        "Authors":  "H You, S Lattmann, D Rhodes, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1093/nar/gkw881",
    },
    {//83
        "Title":    "Applications of Magnetic Tweezers to Studies of NAPs",
        "Authors":  "RS Winardhi, J Yan",
        "Journal":  "The Bacterial Nucleoid",
        "Year":     "2017",
        "DOI":      "https://doi.org/10.1007/978-1-4939-7098-8_14",
    },
    {//82
        "Title":    "Probing Small Molecule Binding to Unfolded Polyprotein Based on its Elasticity and Refolding",
        "Authors":  "RS Winardhi, Q Tang, J Chen, M Yao, J Yan",
        "Journal":  "Biophysical Journal",
        "Year":     "2016",
        "DOI":      "https://doi.org/10.1016/j.bpj.2016.10.031",
    },
    {//81
        "Title":    "FACT Remodels the Tetranucleosomal Unit of Chromatin Fibers for Gene Transcription",
        "Authors":  "W Li, P Chen, J Yu, L Dong, D Liang, J Feng, J Yan, PY Wang, Q Li, Z Zhang, M Li, G Li",
        "Journal":  "Molecular Cell",
        "Year":     "2016",
        "DOI":      "https://doi.org/10.1016/j.molcel.2016.08.024",
    },
    {//80
        "Title":    "A Reversible Association between Smc Coiled Coils Is Regulated by Lysine Acetylation and Is Required for Cohesin Association with the DNA",
        "Authors":  "I Kulemzina, K Ang, X Zhao, JT Teh, V Verma, S Suranthran, AP Chavda, RG Huber, B Eisenhaber, F Eisenhaber, J Yan, D Ivanov",
        "Journal":  "Molecular Cell",
        "Year":     "2016",
        "DOI":      "https://doi.org/10.1016/j.molcel.2016.08.008",
    },
    {//79
        "Title":    "Transfer-matrix calculations of DNA polymer micromechanics under tension and torque constraints",
        "Authors":  "AK Efremov, RS Winardhi, J Yan",
        "Journal":  "Physical Review E",
        "Year":     "2016",
        "DOI":      "https://doi.org/10.1103/PhysRevE.94.032404",
    },
    {//78
        "Title":    "Mechanisms of DNA disentangling by type II topoisomerases. Comment on' Disentangling DNA molecules' by Alexander Vologodskii",
        "Authors":  "J Yan",
        "Journal":  "Physics of Life Reviews",
        "Year":     "2016",
        "DOI":      "https://doi.org/10.1016/j.plrev.2016.09.005",
    },
    {//77
        "Title":    "Recent progress on the mechanics of sharply bent DNA",
        "Authors":  "P Cong, J Yan",
        "Journal":  "Science China Physics, Mechanics & Astronomy",
        "Year":     "2016",
        "DOI":      "https://doi.org/10.1007/s11433-016-0099-0",
    },
    {//76
        "Title":    "The kinetics of force-dependent hybridization and strand-peeling of short DNA fragments",
        "Authors":  "ZJ Yang, GH Yuan, WL Zhai, J Yan, H Chen",
        "Journal":  "Science China Physics, Mechanics & Astronomy",
        "Year":     "2016",
        "DOI":      "https://doi.org/10.1007/s11433-016-0112-0",
    },
    {//75
        "Title":    "The mechanical response of talin",
        "Authors":  "M Yao, BT Goult, B Klapholz, X Hu, CP Toseland, Y Guo, P Cong, MP Sheetz, J Yan",
        "Journal":  "Nature Communications",
        "Year":     "2016",
        "DOI":      "https:doi.org/10.1038/ncomms11966",
    },
    {//74
        "Title":    "The horizontally-acquired response regulator SsrB drives a Salmonella lifestyle switch by relieving biofilm silencing",
        "Authors":  "SK Desai, RS Winardhi, S Periasamy, MM Dykas, J Yan, LJ Kenney",
        "Journal":  "eLife",
        "Year":     "2016",
        "DOI":      "https://doi.org/10.7554/eLife.10747",
    },
    {//73
        "Title":    "Uncovering mechanosensing mechanisms at the single protein level using magnetic tweezers",
        "Authors":  "S Le, R Liu, CT Lim, J Yan",
        "Journal":  "Methods",
        "Year":     "2016",
        "DOI":      "https://doi.org/10.1016/j.ymeth.2015.08.020",
    },
    {//72
        "Title":    "Coil-globule transition of a single semiflexible chain in slitlike confinement",
        "Authors":  "L Dai, CB Renner, J Yan, PS Doyle",
        "Journal":  "Scientific Reports",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1038/srep18438",
    },
    {//71
        "Title":    "Regulation of bacterial DNA packaging in early stationary phase by competitive DNA binding of Dps and IHF",
        "Authors":  "SY Lee, CJ Lim, P Dröge, J Yan",
        "Journal":  "Scientific Reports",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1038/srep18146",
    },
    {//70
        "Title":    "Revisiting the Anomalous Bending Elasticity of Sharply Bent DNA",
        "Authors":  "P Cong, L Dai, H Chen, JRC van der Maarel, PS Doyle, J Yan",
        "Journal":  "Biophysical journal",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1016/j.bpj.2015.10.016",
    },
    {//69
        "Title":    "Catch-bond behavior of DNA condensate under tension",
        "Authors":  "W Li, WJ Wong, CJ Lim, HP Ju,M Li, J Yan, PY Wang",
        "Journal":  "Chinese Physics B",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1088/1674-1056/24/12/128704",
    },
    {//68
        "Title":    "H-NS Regulates Gene Expression and Compacts the Nucleoid: Insights from Single-Molecule Experiments",
        "Authors":  "RS Winardhi, J Yan, LJ Kenney",
        "Journal":  "Biophysical Journal",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1016/j.bpj.2015.08.016",
    },
    {//67
        "Title":    "Disturbance-free rapid solution exchange for magnetic tweezers single-molecule studies",
        "Authors":  "S Le, M Yao, J Chen, AK Efremov, S Azimi, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1093/nar/gkv554",
    },
    {//66
        "Title":    "Complex kinetics of DNA condensation revealed through DNA twist tracing",
        "Authors":  "W Li, WJ Wong, CJ Lim, HP Ju, M Li, J Yan, PY Wang",
        "Journal":  "Physics Review E",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1103/PhysRevE.92.022707",
    },
    {//65
        "Title":    "Transcriptional Repressor TrmBL2 from Thermococcus kodakarensis Forms Filamentous Nucleoprotein Structures and Competes with Histones for DNA Binding in a Salt- and DNA Supercoiling-dependent Manner",
        "Authors":  "AK Efremov, Y Qu, H Maruyama, CJ Lim, K Takeyasu, J Yan",
        "Journal":  "Journal of Biological Chemistry",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1074/jbc.M114.626705",
    },
    {//64
        "Title":    "Mechanochemical regulations of RPA's binding to ssDNA",
        "Authors":  "J Chen, S Le, A Basu, WJ Chazin, J Yan",
        "Journal":  "Scientific Reports",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1038/srep09296",
    },
    {//63
        "Title":    "Dynamics of equilibrium folding and unfolding transitions of titin immunoglobulin domain under constant forces",
        "Authors":  "H Chen, G Yuan, RS Winardhi, M Yao, I Popa, JM Fernandez, J Yan",
        "Journal":  "Journal of the American Chemical Society",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1021/ja5119368",
    },
    {//62
        "Title":    "Talin dependent mechanosensitivity of cell focal adhesions",
        "Authors":  "J Yan, M Yao, BT Goult, MP Sheetz",
        "Journal":  "Cellular and Molecular Bioengineering",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1007/s12195-014-0364-5",
    },
    {//61
        "Title":    "Stability and kinetics of c-MYC promoter G-quadruplexes studied by single-molecule manipulation",
        "Authors":  "H You, J Wu, F Shao, J Yan",
        "Journal":  "Journal of the American Chemical Society",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1021/ja511680u",
    },
    {//60
        "Title":    "The mechanotransduction machinery at work at adherens junctions",
        "Authors":  "B Ladoux, WJ Nelson, J Yan, RM Mege",
        "Journal":  "Integrative Biology",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1039/C5IB00070J",
    },
    {//59
        "Title":    "Thermodynamics of force-dependent folding and unfolding of small protein and nucleic acid structures",
        "Authors":  "M Yao, H Chen, J Yan",
        "Journal":  "Integrative Biology",
        "Year":     "2015",
        "DOI":      "https://doi.org/10.1039/C5IB00038F",
    },
    {//58
        "Title":    "Single-Molecule Study on Histone-Like Nucleoid-Structuring Protein (H-NS) Paralogue in Pseudomonas aeruginosa: MvaU Bears DNA Organization Mode Similarities to MvaT",
        "Authors":  "RS Winardhi, S Castang, SL Dove, J Yan",
        "Journal":  "PLoS ONE",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1371/journal.pone.0112246",
    },
    {//57
        "Title":    "Interconversion between three overstretched DNA structures",
        "Authors":  "X Zhang, Y Qu, H Chen, I Rouzina, S Zhang, PS Doyle, J Yan",
        "Journal":  "Journal of the American Chemical Society",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1021/ja5090805",
    },
    {//56
        "Title":    "Mechanical force antagonizes the inhibitory effects of RecX on RecA filament formation in Mycobacterium tuberculosis",
        "Authors":  "S Le, H Chen, X Zhang, J Chen, KN Patil, K Muniyappa, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1093/nar/gku899",
    },
    {//55
        "Title":    "Dynamics and stability of polymorphic human telomeric G-quadruplex under tension",
        "Authors":  "H You, X Zeng, Y Xu, CJ Lim, AK Efremov, AT Phan, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1093/nar/gku581",
    },
    {//54
        "Title":    "Single-molecule studies on the mechanical interplay between DNA supercoiling and H-NS DNA architectural properties",
        "Authors":  "CJ Lim, LJ Kenney, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1093/nar/gku566",
    },
    {//53
        "Title":    "Force-dependent conformational switch of [alpha]-catenin controls vinculin binding",
        "Authors":  "M Yao, W Qiu, R Liu, AK Efremov, P Cong, R Seddiki, M Payre, CT Lim, B Ladoux, RM Mege, J Yan",
        "Journal":  "Nature Communications",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1038/ncomms5525",
    },
    {//52
        "Title":    "Mechano-chemical selections of two competitive unfolding pathways of a single DNA i-motif",
        "Authors":  "Y Xu, H Chen, Y Qu, AK Efremov, M Li, ZC Ouyang, DS Liu, J Yan",
        "Journal":  "Chinese Physics B",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1088/1674-1056/23/6/068702",
    },
    {//51
        "Title":    "Locus of Enterocyte Effacement-encoded Regulator (Ler) of Pathogenic Escherichia coli Competes Off Histone-like Nucleoid-structuring Protein (H-NS) through Noncooperative DNA Binding",
        "Authors":  "RS Winardhi, R Gulvady, JL Mellies, J Yan",
        "Journal":  "Journal of Biological Chemistry",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1074/jbc.M113.545954",
    },
    {//50
        "Title":    "Mechanical activation of vinculin binding to talin locks talin in an unfolded conformation",
        "Authors":  "M Yao, BT Goult, H Chen, P Cong, MP Sheetz, J Yan",
        "Journal":  "Scientific Reports",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1038/srep04610",
    },
    {//49
        "Title":    "Effect of YOYO-1 on the mechanical properties of DNA",
        "Authors":  "B Kundukad, J Yan, PS Doyle",
        "Journal":  "Soft Matter",
        "Year":     "2014",
        "DOI":      "https://doi.org/10.1039/C4SM02025A",
    },
    {//48
        "Title":    "Mechanosensing of DNA bending in a single specific protein-DNA complex",
        "Authors":  "S Le, H Chen, P Cong, J Lin, P Dröge, J Yan",
        "Journal":  "Scientific Reports",
        "Year":     "2013",
        "DOI":      "https://doi.org/10.1038/srep03508",
    },
    {//47
        "Title":    "Dynamics and Regulation of RecA Polymerization and De-Polymerization on Double-Stranded DNA",
        "Authors":  "H Fu, S Le, K Muniyappa, J Yan",
        "Journal":  "PLoS ONE",
        "Year":     "2013",
        "DOI":      "https://doi.org/10.1371/journal.pone.0066712",
    },
    {//46
        "Title":    "Mechanism of DNA organization by Mycobacterium tuberculosis protein Lsr2",
        "Authors":  "Y Qu, CJ Lim, YR Whang, J Liu, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2013",
        "DOI":      "https://doi.org/10.1093/nar/gkt249",
    },
    {//45
        "Title":    "Mechanical perturbation of filamin A immunoglobulin repeats 20-21 reveals potential non-equilibrium mechanochemical partner binding function",
        "Authors":  "H Chen, S Chandrasekar, MP Sheetz, TP Stossel, F Nakamura, J Yan",
        "Journal":  "Scientific Reports",
        "Year":     "2013",
        "DOI":      "https://doi.org/10.1038/srep01642",
    },
    {//44
        "Title":    "Revealing the competition between peeled ssDNA, melting bubbles, and S-DNA during DNA overstretching by single-molecule calorimetry",
        "Authors":  "X Zhang, H Chen, S Le, I Rouzina, PS Doyle, J Yan",
        "Journal":  "PNAS",
        "Year":     "2013",
        "DOI":      "http://www.pnas.org/content/110/10/3865.short",
    },
    {//43
        "Title":    "Force and ATP hydrolysis dependent regulation of RecA nucleoprotein filament by single-stranded DNA binding protein",
        "Authors":  "H Fu, S Le, H Chen, K Muniyappa, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2013",
        "DOI":      "https://doi.org/10.1093/nar/gks1162",
    },
    {//42
        "Title":    "The nucleoid-associated protein Dan organizes chromosomal DNA through rigid nucleoprotein filament formation in E. coli during anoxia",
        "Authors":  "CJ Lim, SY Lee, J Teramoto, A Ishihama, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2012",
        "DOI":      "https://doi.org/10.1093/nar/gks1126",
    },
    {//41
        "Title":    "Impact of DNA Twist Accumulation on Progressive Helical Wrapping of Torsionally Constrained DNA",
        "Authors":  "W Li, PY Wang, J Yan, M Li",
        "Journal":  "Physical Review Letters",
        "Year":     "2012",
        "DOI":      "https://doi.org/10.1103/PhysRevLett.109.218102",
    },
    {//40
        "Title":    "Physical Organization of DNA by Multiple Non-Specific DNA-Binding Modes of Integration Host Factor (IHF",
        "Authors":  "J Lin, H Chen, P Dröge, J Yan",
        "Journal":  "PLoS ONE",
        "Year":     "2012",
        "DOI":      "https://doi.org/10.1371/journal.pone.0049885",
    },
    {//39
        "Title":    "Single-Molecule DNA Analysis Reveals That Yeast Hop1 Protein Promotes DNA Folding and Synapsis: Implications for Condensation of Meiotic Chromosomes",
        "Authors":  "K Khan, U Karthikeyan, Y Li, J Yan, K Muniyappa",
        "Journal":  "ACS Nano",
        "Year":     "2012",
        "DOI":      "https://doi.org/10.1021/nn3038258",
    },
    {//38
        "Title":    "Nucleoprotein filament formation is the structural basis for bacterial protein H-NS gene silencing",
        "Authors":  "CJ Lim, SY Lee, LJ Kenney, J Yan",
        "Journal":  "Scientific Reports",
        "Year":     "2012",
        "DOI":      "https://doi.org/10.1038/srep00509",
    },
    {//37
        "Title":    "Higher order oligomerization is required for H-NS family member MvaT to form gene-silencing nucleoprotein filament",
        "Authors":  "RS Winardhi, W Fu, S Castang, Y Li, SL Dove, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2012",
        "DOI":      "https://doi.org/10.1093/nar/gks669",
    },
    {//36
        "Title":    "Two distinct overstretched DNA structures revealed by single-molecule thermodynamics measurements",
        "Authors":  "X Zhang, H Chen, H Fu, PS Doyle, J Yan",
        "Journal":  "PNAS",
        "Year":     "2012",
        "DOI":      "http://www.pnas.org/content/109/21/8103.short",
    },
    {//35
        "Title":    "Gene silencing H-NS paralogue StpA forms a rigid protein filament along DNA that blocks DNA accessibility",
        "Authors":  "CJ Lim, YR Whang, LJ Kenney, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2011",
        "DOI":      "https://doi.org/10.1093/nar/gkr1247",
    },
    {//34
        "Title":    "Differential Mechanical Stability of Filamin A Rod Segments",
        "Authors":  "H Chen, X Zhu, P Cong, MP Sheetz, F Nakamura, J Yan",
        "Journal":  "Biophysical Journal",
        "Year":     "2011",
        "DOI":      "https://doi.org/10.1016/j.bpj.2011.07.028",
    },
    {//33
        "Title":    "Atomic force microscope imaging of chromatin assembled in Xenopus laevis egg extract",
        "Authors":  "H Fu, BS Freedman, CT Lim, R Heald, J Yan",
        "Journal":  "Chromosoma",
        "Year":     "2011",
        "DOI":      "https://doi.org/10.1007/s00412-010-0307-4",
    },
    {//32
        "Title":    "Transition dynamics and selection of the distinct S-DNA and strand unpeeling modes of double helix overstretching",
        "Authors":  "H Fu, H Chen, X Zhang, Y Qu, JF Marko, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2011",
        "DOI":      "https://doi.org/10.1093/nar/gkq1278",
    },
    {//31
        "Title":    "Salmonella enterica response regulator SsrB relieves H-NS silencing by displacing H-NS bound in polymerization mode and directly activates transcription",
        "Authors":  "D Walthers, Y Li, Y Liu, G Anand, J Yan, LJ Kenney",
        "Journal":  "Journal of Biological Chemistry",
        "Year":     "2011",
        "DOI":      "https://doi.org/10.1074/jbc.M110.164962",
    },
    {//30
        "Title":    "Improved High-Force Magnetic Tweezers for Stretching and Refolding of Proteins and Short DNA",
        "Authors":  "H Chen, H Fu, X Zhu, P Cong, F Nakamura, J Yan",
        "Journal":  "Biophysical Journal",
        "Year":     "2011",
        "DOI":      "https://doi.org/10.1016/j.bpj.2010.12.3700",
    },
    {//29
        "Title":    "DNA condensates organized by the capsid protein VP15 in White Spot Syndrome Virus",
        "Authors":  "Y Liu, J Wu, H Chen, CL Hew, J Yan",
        "Journal":  "Virology",
        "Year":     "2010",
        "DOI":      "https://doi.org/10.1016/j.virol.2010.09.008",
    },
    {//28
        "Title":    "Non-Harmonic DNA Bending Elasticity is Revealed by Statistics of DNA Minicircle Shapes",
        "Authors":  "H Chen, H Fu, Z Zhou, J Yan",
        "Journal":  "International Journal of Modern Physics B",
        "Year":     "2010",
        "DOI":      "https://doi.org/10.1142/S0217979210056682",
    },
    {//27
        "Title":    "Two distinct overstretched DNA states",
        "Authors":  "H Fu, H Chen, JF Marko, J Yan",
        "Journal":  "Nucleic Acids Research",
        "Year":     "2010",
        "DOI":      "https://doi.org/10.1093/nar/gkq309",
    },
    {//26
        "Title":    "Salt Solution Effects on Overstretching Transitions of DNA Molecules",
        "Authors":  "H Fu, H Chen, J Yan, CT Lim",
        "Journal":  "Journal of Computational and Theoretical Nanoscience",
        "Year":     "2010",
        "DOI":      "https://doi.org/10.1166/jctn.2010.1480",
    },
    {//25
        "Title":    "A divalent switch drives H-NS/DNA-binding conformations between stiffening and bridging modes",
        "Authors":  "Y Liu, H Chen, LJ Kenney, J Yan",
        "Journal":  "Genes & development",
        "Year":     "2010",
        "DOI":      "http://genesdev.cshlp.org/content/24/4/339",
    },
    {//24
        "Title":    "Temperature dependence of circular DNA topological states",
        "Authors":  "H Chen, Y Liu, Z Zhou, L Hu, ZC Ou-Yang, J Yan",
        "Journal":  "Physical Review E",
        "Year":     "2009",
        "DOI":      "https://doi.org/10.1103/PhysRevE.79.041926",
    },
    {//23
        "Title":    "A Solution to a Single Molecular Experiment Problem",
        "Authors":  "Y Liu, H Chen, L Hu, ZC Ou-Yang, J Yan",
        "Journal":  "Communications in Computatoinal Physics",
        "Year":     "2009",
        "DOI":      "http://ir.itp.ac.cn/handle/311006/5254",
    },
    {//22
        "Title":    "A contractile DNA machine",
        "Authors":  "D Lubrich, J Lin, J Yan",
        "Journal":  "Angewandte Chemie International Edition",
        "Year":     "2008",
        "DOI":      "https://doi.org/10.1002/anie.200800476",
    },
    {//21
        "Title":    "Effects of kink and flexible hinge defects on mechanical responses of short double-stranded DNA molecules",
        "Authors":  "H Chen, J Yan",
        "Journal":  "Physical Review E",
        "Year":     "2008",
        "DOI":      "https://doi.org/10.1103/PhysRevE.77.041907",
    },
    {//20
        "Title":    "Nucleosome hopping and sliding kinetics determined from dynamics of single chromatin fibers in Xenopus egg extracts",
        "Authors":  "P Ranjith, J Yan, JF Marko",
        "Journal":  "PNAS",
        "Year":     "2007",
        "DOI":      "http://www.pnas.org/content/104/34/13649.short",
    },
    {//19
        "Title":    "A divalent metal-mediated switch controlling protein-induced DNA bending",
        "Authors":  "Q Bao, H Chen, Y Liu, J Yan, P Dröge, CA Davey",
        "Journal":  "Journal of Molecular Biology",
        "Year":     "2007",
        "DOI":      "https://doi.org/10.1016/j.jmb.2006.09.082",
    },
    {//18
        "Title":    "Micromanipulation studies of chromatin fibers in Xenopus egg extracts reveal ATP-dependent chromatin assembly dynamics",
        "Authors":  "J Yan, TJ Maresca, D Skoko, CD Adams, B Xiao, MO Christensen, R Heald, JF Marko",
        "Journal":  "Molecular Biology of the Cell",
        "Year":     "2007",
        "DOI":      "https://doi.org/10.1091/mbc.E06-09-0800",
    },
    {//17
        "Title":    "Mechanism of chromosome compaction and looping by the Escherichia coli nucleoid protein Fis",
        "Authors":  "D Skoko, D Yoo, H Bai, B Schnurr, J Yan, SM McLeod, JF Marko, RC Johnson",
        "Journal":  "Journal of Molecular Biology",
        "Year":     "2006",
        "DOI":      "https://doi.org/10.1016/j.jmb.2006.09.043",
    },
    {//16
        "Title":    "Compaction dynamics of single DNA molecules under tension",
        "Authors":  "WB Fu, XL Wang, XH Zhang, SY Ran, J Yan, M Li",
        "Journal":  "Journal of the American Chemical Society",
        "Year":     "2006",
        "DOI":      "https://doi.org/10.1021/ja064305a",
    },
    {//15
        "Title":    "Low-force DNA condensation and discontinuous high-force decondensation reveal a loop-stabilizing function of the protein Fis",
        "Authors":  "D Skoko, J Yan, RC Johnson, JF Marko",
        "Journal":  "Physical Review Letters",
        "Year":     "2005",
        "DOI":      "https://doi.org/10.1103/PhysRevLett.95.208101",
    },
    {//14
        "Title":    "Statistics of loop formation along double helix DNAs",
        "Authors":  "J Yan, R Kawamura, JF Marko",
        "Journal":  "Physical Review E",
        "Year":     "2005",
        "DOI":      "https://doi.org/10.1103/PhysRevE.71.061905",
    },
    {//13
        "Title":    "Defining a centromere-like element in Bacillus subtilis by identifying the binding sites for the chromosome-anchoring protein RacA",
        "Authors":  "S Ben-Yehuda, M Fujita, XS Liu, B Gorbatyuk, D Skoko, J Yan, JF Marko, JS Liu, P Eichenberger, DZ Rudner, R Losick",
        "Journal":  "Molecular cell",
        "Year":     "2005",
        "DOI":      "https://doi.org/10.1016/j.molcel.2005.02.023",
    },
    {//12
        "Title":    "Localized single-stranded bubble mechanism for cyclization of short double helix DNA",
        "Authors":  "J Yan, JF Marko",
        "Journal":  "Physical Review Letters",
        "Year":     "2004",
        "DOI":      "https://doi.org/10.1103/PhysRevLett.93.108108",
    },
    {//11
        "Title":    "Overstretching and force-driven strand separation of double-helix DNA",
        "Authors":  "S Cocco, J Yan, JF Léger, D Chatenay, JF Marko",
        "Journal":  "Physical Review E",
        "Year":     "2004",
        "DOI":      "https://doi.org/10.1103/PhysRevE.70.011910",
    },
    {//10
        "Title":    "Near-field-magnetic-tweezer manipulation of single DNA molecules",
        "Authors":  "J Yan, D Skoko, JF Marko",
        "Journal":  "Physical Review E",
        "Year":     "2004",
        "DOI":      "https://doi.org/10.1103/PhysRevE.70.011905",
    },
    {//9
        "Title":    "Effects of DNA-distorting proteins on DNA elastic response",
        "Authors":  "J Yan, JF Marko",
        "Journal":  "Physical Review E",
        "Year":     "2003",
        "DOI":      "https://doi.org/10.1103/PhysRevE.68.011905",
    },
    {//8
        "Title":    "Force-extension behavior of folding polymers",
        "Authors":  "S Cocco, JF Marko, R Monasson, A Sarkar, J Yan",
        "Journal":  "The European Physical Journal E",
        "Year":     "2003",
        "DOI":      "https://doi.org/10.1140/epje/i2002-10113-2",
    },
    {//7
        "Title":    "Kinetic proofreading can explain the supression of supercoiling of circular DNA molecules by type-II topoisomerases",
        "Authors":  "J Yan, MO Magnasco, JF Marko",
        "Journal":  "Physical Review E",
        "Year":     "2001",
        "DOI":      "https://doi.org/10.1103/PhysRevE.63.031909",
    },
    {//6
        "Title":    "A kinetic proofreading mechanism for disentanglement of DNA by topoisomerases",
        "Authors":  "J Yan, MO Magnasco, JF Marko",
        "Journal":  "Nature",
        "Year":     "1999",
        "DOI":      "https://doi.org/10.1038/44872",
    },
    {//5
        "Title":    "Numerical observation of nonaxisymmetric vesicles in fluid membranes",
        "Authors":  "J Yan, Q Liu, J Liu, ZC Ouyang",
        "Journal":  "Physical Review E",
        "Year":     "1998",
        "DOI":      "https://doi.org/10.1103/PhysRevE.58.4730",
    },
    {//4
        "Title":    "Instability and periodic deformation in bilayer membranes induced by freezing",
        "Authors":  "J Yan, H Zhou, ZC Ouyang",
        "Journal":  "Modern Physics Letters B",
        "Year":     "1998",
        "DOI":      "https://doi.org/10.1142/S0217984998000202",
    },
    {//3
        "Title":    "Stabilizing unstable orbits",
        "Authors":  "H Zhao, Y Wang, J Yan",
        "Journal":  "Physical Letters A",
        "Year":     "1997",
        "DOI":      "https://doi.org/10.1016/S0375-9601(97)00681-6",
    },
    {//2
        "Title":    "Nonlinear differential delay equations using the Poincaré section technique",
        "Authors":  "H Zhao, F Zhang, J Yan, Y Wang",
        "Journal":  "Physical Review E",
        "Year":     "1996",
        "DOI":      "https://doi.org/10.1103/PhysRevE.54.6925",
    },
    {//1
        "Title":    "General method of controlling chaos",
        "Authors":  "H Zhao, J Yan, J Wang, Y Wang",
        "Journal":  "Physical Review E",
        "Year":     "1996",
        "DOI":      "https://doi.org/10.1103/PhysRevE.53.299",
    },

];
